import type { Metadata } from "next";
import "../globals.css";


import Header from "@/components/header";
import Footer from "@/components/footer";
export const metadata: Metadata = {
  title: "Elite Technology Digital Solutions",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="max-w-[1500px] mx-auto"
        style={{ fontFamily: "sans-serif" }}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
